### ISSUE TITLE
Contribute the Flycheck syntax checker to Flycheck

### ISSUE THREAD

**Issue by lunaryorn** [ptrv/processing2-emacs#11]
Hey, 

would you like to contribute the Flycheck syntax checker in this project to Flycheck itself, to support processing out of the box?

**Comment by ptrv** [comment]
@lunaryorn Sure, would be great to have it in flycheck.

I'll set up a PR as soon as possible.

**Comment by lunaryorn** [comment]
@ptrv I can also just copy the definition by myself and commit with your name, if that's easier for you.

**Comment by ptrv** [comment]
@lunaryorn Feel free to do that. Then, I'll only have to make a PR to melpa to remove the recipe.

**Comment by lunaryorn** [comment]
@ptrv I can also do that :relaxed:  IOW, I'll take care of everything.  I just needed your permission :relaxed:

**Comment by ptrv** [comment]
@lunaryorn Nice! Thanks! Go ahead!

**Comment by lunaryorn** [comment]
@ptrv I'll even open a PR here to remove the checker from this repo :sunglasses: so just sit back and relax :smile:

**Comment by ptrv** [comment]
@lunaryorn :D

**Comment by lunaryorn** [comment]
@ptrv I merged flycheck/flycheck#812; the syntax checker is now part of Flycheck.  I opened PRs to this repo and to MELPA to remove flycheck-processing.

Thank you very much for your support and for your help in the integration :heart: :+1: :clap:

**Comment by ptrv** [comment]
@lunaryorn Thank you for adding the checker to Flycheck! /cc @myrjola
