### ISSUE TITLE
Why isn't processing-company in MELPA?

### ISSUE THREAD

**Issue by myrjola** [ptrv/processing2-emacs#7]
Looking at the [recipe](https://github.com/milkypostman/melpa/blob/master/recipes/processing-mode) only processing-mode.el is there.

**Comment by ptrv** [comment]
`processing-company.el` is not a real completion backend, it's just the config to set up `company-keyword` backend. I think that's why I haven't put it to melpa.

**Comment by myrjola** [comment]
I think that file serves as a good base for real autocompletion. Of course it won't be easy to implement that, but I think it won't hurt to have it included by default. It shouldn't break anything as it is not required by `processing-mode.el`. Or will this force a dependency on company-mode because of bytecompiling?

**Comment by ptrv** [comment]
@myrjola Yes adding `processing-company.el` to `processing-mode` would require to add `company-mode` as dependency to `processing-mode`, which I want to avoid.

On the other hand there are only a few lines of code in `processing-company.el` and could be added to your config. There will be no more development on it anyways probably.

**Comment by myrjola** [comment]
Ok. I consider this issue resolved.
